language: go
sudo: false

go:
  - "1.x"
  - "1.17.x"
  - "1.18.x"

install: true

script:
  - env GO111MODULE=on go test ./...

after_success:
  - env GO111MODULE=on go test -coverprofile=coverage.txt -covermode=atomic ./...
  - bash <(curl -s https://codecov.io/bash)
